/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DeliveryStatus = IDL.Variant({
  'assigned' : IDL.Null,
  'in_transit' : IDL.Null,
  'delivered' : IDL.Null,
  'failed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Delivery = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : DeliveryStatus,
  'assignedAt' : Timestamp,
  'orderId' : IDL.Nat,
  'itemsCount' : IDL.Nat,
  'address' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
  'processing' : IDL.Null,
  'returned' : IDL.Null,
});
export const UserId = IDL.Principal;
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'total' : IDL.Float64,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'items' : IDL.Vec(OrderItem),
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
});
export const ShipmentStatus = IDL.Variant({
  'dispatched' : IDL.Null,
  'arriving' : IDL.Null,
  'processing' : IDL.Null,
  'received' : IDL.Null,
});
export const Shipment = IDL.Record({
  'id' : IDL.Nat,
  'productsCount' : IDL.Nat,
  'status' : ShipmentStatus,
  'destination' : IDL.Text,
  'origin' : IDL.Text,
  'receivedAt' : IDL.Opt(Timestamp),
});
export const TicketStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'closed' : IDL.Null,
  'in_progress' : IDL.Null,
  'open' : IDL.Null,
});
export const TicketMessage = IDL.Record({
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
});
export const TicketPriority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'urgent' : IDL.Null,
  'medium' : IDL.Null,
});
export const Ticket = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : TicketStatus,
  'subject' : IDL.Text,
  'messages' : IDL.Vec(TicketMessage),
  'createdAt' : Timestamp,
  'customerId' : UserId,
  'priority' : TicketPriority,
});
export const VendorStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Vendor = IDL.Record({
  'id' : IDL.Nat,
  'productsCount' : IDL.Nat,
  'status' : VendorStatus,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
  'companyName' : IDL.Text,
  'brandName' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeliveries' : IDL.Func([], [IDL.Vec(Delivery)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
  'getTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
  'getVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateDeliveryStatus' : IDL.Func([IDL.Nat, DeliveryStatus], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateShipmentStatus' : IDL.Func([IDL.Nat, ShipmentStatus], [], []),
  'updateTicketStatus' : IDL.Func([IDL.Nat, TicketStatus], [], []),
  'updateVendorStatus' : IDL.Func([IDL.Nat, VendorStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DeliveryStatus = IDL.Variant({
    'assigned' : IDL.Null,
    'in_transit' : IDL.Null,
    'delivered' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Delivery = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : DeliveryStatus,
    'assignedAt' : Timestamp,
    'orderId' : IDL.Nat,
    'itemsCount' : IDL.Nat,
    'address' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
    'processing' : IDL.Null,
    'returned' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'total' : IDL.Float64,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'items' : IDL.Vec(OrderItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
  });
  const ShipmentStatus = IDL.Variant({
    'dispatched' : IDL.Null,
    'arriving' : IDL.Null,
    'processing' : IDL.Null,
    'received' : IDL.Null,
  });
  const Shipment = IDL.Record({
    'id' : IDL.Nat,
    'productsCount' : IDL.Nat,
    'status' : ShipmentStatus,
    'destination' : IDL.Text,
    'origin' : IDL.Text,
    'receivedAt' : IDL.Opt(Timestamp),
  });
  const TicketStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'closed' : IDL.Null,
    'in_progress' : IDL.Null,
    'open' : IDL.Null,
  });
  const TicketMessage = IDL.Record({
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const TicketPriority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'urgent' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Ticket = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : TicketStatus,
    'subject' : IDL.Text,
    'messages' : IDL.Vec(TicketMessage),
    'createdAt' : Timestamp,
    'customerId' : UserId,
    'priority' : TicketPriority,
  });
  const VendorStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Vendor = IDL.Record({
    'id' : IDL.Nat,
    'productsCount' : IDL.Nat,
    'status' : VendorStatus,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
    'companyName' : IDL.Text,
    'brandName' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeliveries' : IDL.Func([], [IDL.Vec(Delivery)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getShipments' : IDL.Func([], [IDL.Vec(Shipment)], ['query']),
    'getTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
    'getVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateDeliveryStatus' : IDL.Func([IDL.Nat, DeliveryStatus], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateShipmentStatus' : IDL.Func([IDL.Nat, ShipmentStatus], [], []),
    'updateTicketStatus' : IDL.Func([IDL.Nat, TicketStatus], [], []),
    'updateVendorStatus' : IDL.Func([IDL.Nat, VendorStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };