/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Delivery {
  'id' : bigint,
  'customerName' : string,
  'status' : DeliveryStatus,
  'assignedAt' : Timestamp,
  'orderId' : bigint,
  'itemsCount' : bigint,
  'address' : string,
}
export type DeliveryStatus = { 'assigned' : null } |
  { 'in_transit' : null } |
  { 'delivered' : null } |
  { 'failed' : null };
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'total' : number,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'name' : string,
  'productId' : bigint,
  'quantity' : bigint,
  'price' : number,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null } |
  { 'processing' : null } |
  { 'returned' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'imageUrl' : string,
  'category' : string,
  'rating' : number,
  'price' : number,
}
export interface Shipment {
  'id' : bigint,
  'productsCount' : bigint,
  'status' : ShipmentStatus,
  'destination' : string,
  'origin' : string,
  'receivedAt' : [] | [Timestamp],
}
export type ShipmentStatus = { 'dispatched' : null } |
  { 'arriving' : null } |
  { 'processing' : null } |
  { 'received' : null };
export interface Ticket {
  'id' : bigint,
  'customerName' : string,
  'status' : TicketStatus,
  'subject' : string,
  'messages' : Array<TicketMessage>,
  'createdAt' : Timestamp,
  'customerId' : UserId,
  'priority' : TicketPriority,
}
export interface TicketMessage {
  'sender' : string,
  'message' : string,
  'timestamp' : Timestamp,
}
export type TicketPriority = { 'low' : null } |
  { 'high' : null } |
  { 'urgent' : null } |
  { 'medium' : null };
export type TicketStatus = { 'resolved' : null } |
  { 'closed' : null } |
  { 'in_progress' : null } |
  { 'open' : null };
export type Timestamp = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'id' : bigint,
  'productsCount' : bigint,
  'status' : VendorStatus,
  'createdAt' : Timestamp,
  'email' : string,
  'companyName' : string,
  'brandName' : string,
}
export type VendorStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDeliveries' : ActorMethod<[], Array<Delivery>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getShipments' : ActorMethod<[], Array<Shipment>>,
  'getTickets' : ActorMethod<[], Array<Ticket>>,
  'getVendors' : ActorMethod<[], Array<Vendor>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateDeliveryStatus' : ActorMethod<[bigint, DeliveryStatus], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateShipmentStatus' : ActorMethod<[bigint, ShipmentStatus], undefined>,
  'updateTicketStatus' : ActorMethod<[bigint, TicketStatus], undefined>,
  'updateVendorStatus' : ActorMethod<[bigint, VendorStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];