import type { Product } from "@/backend";

export interface MockProduct extends Product {
  company: string;
  colour: string[];
  connectivity: "wired" | "wireless" | "bluetooth";
  compatibility: string[];
  freeDelivery: boolean;
  deliveryDays: 1 | 2 | 3;
  tags: string[];
  hasDeal: boolean;
  hasCoupon: boolean;
}

export const MOCK_PRODUCTS: MockProduct[] = [
  {
    id: BigInt(1),
    name: "Anker PowerCore 10000 Portable Charger",
    description:
      "Ultra-compact power bank with high-speed charging technology. Fits in your pocket for on-the-go charging.",
    stock: BigInt(45),
    imageUrl: "https://m.media-amazon.com/images/I/71qdNrZjJzL._AC_SX679_.jpg",
    category: "Power Banks",
    rating: 4.6,
    price: 1999,
    brand: "Anker",
    company: "Anker Innovations",
    originalPrice: 3499,
    discountPercent: 43n,
    colour: ["Black", "White"],
    connectivity: "wired",
    compatibility: [
      "iPhone",
      "Samsung Galaxy",
      "OnePlus",
      "Xiaomi/Redmi",
      "Realme",
    ],
    freeDelivery: true,
    deliveryDays: 1,
    tags: ["Power Banks"],
    hasDeal: true,
    hasCoupon: false,
  },
  {
    id: BigInt(2),
    name: "boAt Airdopes 141 Wireless Earbuds",
    description:
      "True wireless earbuds with 42 hours playtime, BEAST Mode gaming, and environmental noise cancellation.",
    stock: BigInt(120),
    imageUrl: "https://m.media-amazon.com/images/I/61RydSEm-bL._AC_SX679_.jpg",
    category: "Audio",
    rating: 4.3,
    price: 1299,
    brand: "boAt",
    company: "boAt Lifestyle",
    originalPrice: 2990,
    discountPercent: 57n,
    colour: ["Black", "Blue", "White"],
    connectivity: "bluetooth",
    compatibility: [
      "iPhone",
      "Samsung Galaxy",
      "OnePlus",
      "Xiaomi/Redmi",
      "Realme",
      "All Brands",
    ],
    freeDelivery: true,
    deliveryDays: 1,
    tags: ["Earbuds"],
    hasDeal: true,
    hasCoupon: true,
  },
  {
    id: BigInt(3),
    name: "Belkin 3-in-1 Wireless Charger MagSafe",
    description:
      "Charge iPhone, Apple Watch, and AirPods simultaneously. Made for MagSafe with precise alignment.",
    stock: BigInt(30),
    imageUrl: "https://m.media-amazon.com/images/I/71AwMRLdWXL._AC_SX679_.jpg",
    category: "Chargers",
    rating: 4.5,
    price: 6999,
    brand: "Belkin",
    company: "Belkin International",
    originalPrice: 8999,
    discountPercent: 22n,
    colour: ["White", "Black"],
    connectivity: "wireless",
    compatibility: ["iPhone", "All Brands"],
    freeDelivery: true,
    deliveryDays: 2,
    tags: ["Wireless Chargers"],
    hasDeal: false,
    hasCoupon: false,
  },
  {
    id: BigInt(4),
    name: "Samsung 45W Super Fast Charger USB-C",
    description:
      "45W Super Fast Charging 2.0 compatible wall adapter. Charges Galaxy S21+ to 50% in just 26 minutes.",
    stock: BigInt(75),
    imageUrl: "https://m.media-amazon.com/images/I/71eBsHFGkDL._AC_SX679_.jpg",
    category: "Chargers",
    rating: 4.4,
    price: 1799,
    brand: "Samsung",
    company: "Samsung Electronics",
    originalPrice: 2499,
    discountPercent: 28n,
    colour: ["Black", "White"],
    connectivity: "wired",
    compatibility: ["Samsung Galaxy", "OnePlus", "Xiaomi/Redmi", "All Brands"],
    freeDelivery: true,
    deliveryDays: 1,
    tags: ["Wireless Chargers"],
    hasDeal: true,
    hasCoupon: false,
  },
  {
    id: BigInt(5),
    name: "Spigen Ultra Hybrid iPhone 15 Case",
    description:
      "Military-grade protection with a clear back that showcases your iPhone design. Air Cushion Technology.",
    stock: BigInt(200),
    imageUrl: "https://m.media-amazon.com/images/I/71tFPJyGnBL._AC_SX679_.jpg",
    category: "Phone Cases",
    rating: 4.7,
    price: 899,
    brand: "Spigen",
    company: "Spigen Inc",
    originalPrice: 1499,
    discountPercent: 40n,
    colour: ["Clear", "Black"],
    connectivity: "wired",
    compatibility: ["iPhone"],
    freeDelivery: false,
    deliveryDays: 2,
    tags: ["Phone Cases"],
    hasDeal: false,
    hasCoupon: true,
  },
  {
    id: BigInt(6),
    name: "OnePlus 80W SUPERVOOC Charger",
    description:
      "80W ultra-fast charging with SUPERVOOC technology. Smart protection chip prevents overcharging.",
    stock: BigInt(50),
    imageUrl: "https://m.media-amazon.com/images/I/51eSWFkBvGL._AC_SX679_.jpg",
    category: "Chargers",
    rating: 4.5,
    price: 1299,
    brand: "OnePlus",
    company: "OnePlus Technology",
    originalPrice: 1799,
    discountPercent: 28n,
    colour: ["Black", "Red"],
    connectivity: "wired",
    compatibility: ["OnePlus", "Samsung Galaxy", "Xiaomi/Redmi", "All Brands"],
    freeDelivery: true,
    deliveryDays: 1,
    tags: ["Wireless Chargers"],
    hasDeal: true,
    hasCoupon: false,
  },
  {
    id: BigInt(7),
    name: "Tempered Glass Screen Protector iPhone 15 Pro",
    description:
      "9H hardness tempered glass with oleophobic coating. Perfect fit with no bubbles.",
    stock: BigInt(300),
    imageUrl: "https://m.media-amazon.com/images/I/71U-aGVMPTL._AC_SX679_.jpg",
    category: "Screen Protectors",
    rating: 4.2,
    price: 299,
    brand: "Spigen",
    company: "Spigen Inc",
    originalPrice: 599,
    discountPercent: 50n,
    colour: ["Clear"],
    connectivity: "wired",
    compatibility: ["iPhone"],
    freeDelivery: false,
    deliveryDays: 2,
    tags: ["Screen Protectors"],
    hasDeal: true,
    hasCoupon: false,
  },
  {
    id: BigInt(8),
    name: "JBL Tune 510BT Wireless Headphones",
    description:
      "40-hour battery life with JBL Pure Bass Sound. Lightweight foldable design with Hands-Free calling.",
    stock: BigInt(60),
    imageUrl: "https://m.media-amazon.com/images/I/71JDtMoFiDL._AC_SX679_.jpg",
    category: "Audio",
    rating: 4.4,
    price: 2499,
    brand: "JBL",
    company: "JBL/Harman",
    originalPrice: 3999,
    discountPercent: 38n,
    colour: ["Black", "Blue", "Pink", "White"],
    connectivity: "bluetooth",
    compatibility: ["iPhone", "Samsung Galaxy", "All Brands"],
    freeDelivery: true,
    deliveryDays: 1,
    tags: ["Earbuds"],
    hasDeal: true,
    hasCoupon: true,
  },
  {
    id: BigInt(9),
    name: "Anker USB-C to Lightning Cable 6ft",
    description:
      "MFi certified cable for fast charging iPhone up to 18W. Toughened nylon braid for 3x more durability.",
    stock: BigInt(180),
    imageUrl: "https://m.media-amazon.com/images/I/61k7sW0JwBL._AC_SX679_.jpg",
    category: "Cables",
    rating: 4.5,
    price: 799,
    brand: "Anker",
    company: "Anker Innovations",
    originalPrice: 1299,
    discountPercent: 38n,
    colour: ["Black", "White"],
    connectivity: "wired",
    compatibility: ["iPhone", "All Brands"],
    freeDelivery: true,
    deliveryDays: 1,
    tags: ["USB-C Cables"],
    hasDeal: false,
    hasCoupon: false,
  },
  {
    id: BigInt(10),
    name: "Xiaomi Redmi Buds 4 Active TWS Earbuds",
    description:
      "IP54 water resistance, 28H total battery, Bluetooth 5.3, and deep bass technology for immersive sound.",
    stock: BigInt(90),
    imageUrl: "https://m.media-amazon.com/images/I/71aPZlV+MsL._AC_SX679_.jpg",
    category: "Audio",
    rating: 4.1,
    price: 999,
    brand: "Xiaomi",
    company: "Xiaomi Corporation",
    originalPrice: 1799,
    discountPercent: 44n,
    colour: ["Black", "White", "Blue"],
    connectivity: "bluetooth",
    compatibility: ["Xiaomi/Redmi", "Samsung Galaxy", "All Brands"],
    freeDelivery: true,
    deliveryDays: 2,
    tags: ["Earbuds"],
    hasDeal: true,
    hasCoupon: false,
  },
  {
    id: BigInt(11),
    name: "PopSockets PopGrip Phone Stand & Grip",
    description:
      "Expand for a grip, collapse for wireless charging or to fit in your pocket. Compatible with most cases.",
    stock: BigInt(250),
    imageUrl: "https://m.media-amazon.com/images/I/51jqMUjV6DL._AC_SX679_.jpg",
    category: "Accessories",
    rating: 4.3,
    price: 499,
    brand: "Spigen",
    company: "Spigen Inc",
    originalPrice: 799,
    discountPercent: 38n,
    colour: ["Black", "Pink", "Blue", "Red"],
    connectivity: "wired",
    compatibility: ["iPhone", "Samsung Galaxy", "All Brands"],
    freeDelivery: false,
    deliveryDays: 2,
    tags: ["Phone Stands"],
    hasDeal: false,
    hasCoupon: true,
  },
  {
    id: BigInt(12),
    name: "Realme 33W Dart Charger with USB-C Cable",
    description:
      "33W Dart Charge technology. Complete charge in about 65 minutes. Smart protection for long battery life.",
    stock: BigInt(110),
    imageUrl: "https://m.media-amazon.com/images/I/41M8JfKvBpL._AC_SX679_.jpg",
    category: "Chargers",
    rating: 4.2,
    price: 799,
    brand: "Realme",
    company: "Realme Mobiles",
    originalPrice: 1199,
    discountPercent: 33n,
    colour: ["Yellow", "Black"],
    connectivity: "wired",
    compatibility: ["Realme", "Samsung Galaxy", "Xiaomi/Redmi", "All Brands"],
    freeDelivery: true,
    deliveryDays: 1,
    tags: ["USB-C Cables"],
    hasDeal: false,
    hasCoupon: false,
  },
  {
    id: BigInt(13),
    name: "Bose QuietComfort 45 Noise Cancelling Headphones",
    description:
      "World-class noise cancellation with hi-fi audio. Aware Mode lets the outside world in. 24-hour battery.",
    stock: BigInt(25),
    imageUrl: "https://m.media-amazon.com/images/I/61sooMeB7RL._AC_SX679_.jpg",
    category: "Audio",
    rating: 4.8,
    price: 24999,
    brand: "Bose",
    company: "Bose Corporation",
    originalPrice: 34900,
    discountPercent: 28n,
    colour: ["Black", "White", "Grey"],
    connectivity: "bluetooth",
    compatibility: ["iPhone", "Samsung Galaxy", "All Brands"],
    freeDelivery: true,
    deliveryDays: 2,
    tags: ["Earbuds"],
    hasDeal: false,
    hasCoupon: false,
  },
  {
    id: BigInt(14),
    name: "Zebronics ZEB-Ring Wireless Car Charger Mount",
    description:
      "15W wireless charging with 360° rotation. Compatible with all Qi-enabled devices. Dashboard or vent mount.",
    stock: BigInt(70),
    imageUrl: "https://m.media-amazon.com/images/I/71R7mHUr4YL._AC_SX679_.jpg",
    category: "Car Accessories",
    rating: 4.0,
    price: 699,
    brand: "Zebronics",
    company: "Zebronics India",
    originalPrice: 1499,
    discountPercent: 53n,
    colour: ["Black", "Silver"],
    connectivity: "wireless",
    compatibility: ["iPhone", "Samsung Galaxy", "Xiaomi/Redmi", "All Brands"],
    freeDelivery: false,
    deliveryDays: 2,
    tags: ["Car Mounts", "Wireless Chargers"],
    hasDeal: true,
    hasCoupon: false,
  },
  {
    id: BigInt(15),
    name: "Sony WF-1000XM5 True Wireless Earbuds",
    description:
      "Industry-leading noise cancellation, crystal clear calls, and up to 36 hours of battery with the case.",
    stock: BigInt(15),
    imageUrl: "https://m.media-amazon.com/images/I/61sJ8q0IKUL._AC_SX679_.jpg",
    category: "Audio",
    rating: 4.7,
    price: 16990,
    brand: "Sony",
    company: "Sony Corporation",
    originalPrice: 24990,
    discountPercent: 32n,
    colour: ["Black", "Silver"],
    connectivity: "bluetooth",
    compatibility: ["iPhone", "Samsung Galaxy", "All Brands"],
    freeDelivery: true,
    deliveryDays: 1,
    tags: ["Earbuds"],
    hasDeal: false,
    hasCoupon: false,
  },
  {
    id: BigInt(16),
    name: "Mivi ThunderBeats 4 Earphones",
    description:
      "13mm dynamic drivers, 10H playtime, Type-C charging, and ergonomic fit for active users.",
    stock: BigInt(150),
    imageUrl: "https://m.media-amazon.com/images/I/61rl5kSHoUL._AC_SX679_.jpg",
    category: "Audio",
    rating: 3.9,
    price: 499,
    brand: "Mivi",
    company: "Mivi Technologies",
    originalPrice: 999,
    discountPercent: 50n,
    colour: ["Black", "Blue", "Red"],
    connectivity: "wired",
    compatibility: ["Samsung Galaxy", "Xiaomi/Redmi", "Realme", "All Brands"],
    freeDelivery: true,
    deliveryDays: 2,
    tags: ["Earbuds"],
    hasDeal: true,
    hasCoupon: true,
  },
  {
    id: BigInt(17),
    name: "Portronics Toad 23 Webcam 1080p HD",
    description:
      "Full HD 1080p with built-in stereo microphone. Plug-and-play USB. Ideal for video calls and streaming.",
    stock: BigInt(40),
    imageUrl: "https://m.media-amazon.com/images/I/61OfmJP9w-L._AC_SX679_.jpg",
    category: "Webcams",
    rating: 4.1,
    price: 1299,
    brand: "Portronics",
    company: "Portronics Digital",
    originalPrice: 2499,
    discountPercent: 48n,
    colour: ["Black"],
    connectivity: "wired",
    compatibility: ["All Brands"],
    freeDelivery: true,
    deliveryDays: 2,
    tags: ["Webcams"],
    hasDeal: false,
    hasCoupon: false,
  },
  {
    id: BigInt(18),
    name: "pTron Bullet Pro USB-C Wired Earphones",
    description:
      "13mm driver with deep bass, in-line mic and volume control, magnetic earbud backs, tangle-free cable.",
    stock: BigInt(200),
    imageUrl: "https://m.media-amazon.com/images/I/51sHxvkMgpL._AC_SX679_.jpg",
    category: "Audio",
    rating: 3.8,
    price: 249,
    brand: "pTron",
    company: "pTron Innovations",
    originalPrice: 599,
    discountPercent: 58n,
    colour: ["Black", "Blue", "Green"],
    connectivity: "wired",
    compatibility: ["Samsung Galaxy", "Xiaomi/Redmi", "Realme", "All Brands"],
    freeDelivery: false,
    deliveryDays: 3,
    tags: ["Earbuds"],
    hasDeal: true,
    hasCoupon: false,
  },
  {
    id: BigInt(19),
    name: "Skullcandy Crusher Evo Wireless Headphones",
    description:
      "Personal Sound with Adjustable Sensory Bass, 40-hour battery, rapid charge, and Tile integration.",
    stock: BigInt(35),
    imageUrl: "https://m.media-amazon.com/images/I/81c+M9kJ+5L._AC_SX679_.jpg",
    category: "Audio",
    rating: 4.5,
    price: 8499,
    brand: "Skullcandy",
    company: "Skullcandy Inc",
    originalPrice: 12999,
    discountPercent: 35n,
    colour: ["Black", "Grey", "Blue"],
    connectivity: "bluetooth",
    compatibility: ["iPhone", "Samsung Galaxy", "All Brands"],
    freeDelivery: true,
    deliveryDays: 2,
    tags: ["Earbuds"],
    hasDeal: false,
    hasCoupon: true,
  },
  {
    id: BigInt(20),
    name: "Apple AirTag (Pack of 4)",
    description:
      "Keep track of your belongings in the Find My app. IP67 water and dust resistant, replaceable battery.",
    stock: BigInt(55),
    imageUrl: "https://m.media-amazon.com/images/I/71gHFhC3KkL._AC_SX679_.jpg",
    category: "Accessories",
    rating: 4.6,
    price: 8900,
    brand: "Apple",
    company: "Apple Inc",
    originalPrice: 11900,
    discountPercent: 25n,
    colour: ["White", "Silver"],
    connectivity: "wireless",
    compatibility: ["iPhone"],
    freeDelivery: true,
    deliveryDays: 1,
    tags: [],
    hasDeal: false,
    hasCoupon: false,
  },
  {
    id: BigInt(21),
    name: "Anker 543 USB-C Hub 6-in-1",
    description:
      "Expand your USB-C devices with 4K HDMI, 2 USB-A ports, SD & microSD card slots, and USB-C Power Delivery.",
    stock: BigInt(65),
    imageUrl: "https://m.media-amazon.com/images/I/71J2JGcMPNL._AC_SX679_.jpg",
    category: "Cables",
    rating: 4.4,
    price: 2499,
    brand: "Anker",
    company: "Anker Innovations",
    originalPrice: 3999,
    discountPercent: 38n,
    colour: ["Black", "Silver"],
    connectivity: "wired",
    compatibility: ["All Brands"],
    freeDelivery: true,
    deliveryDays: 1,
    tags: ["USB-C Cables"],
    hasDeal: false,
    hasCoupon: false,
  },
  {
    id: BigInt(22),
    name: "Ring Light 10 Inch with Tripod Stand",
    description:
      "3 light modes, 11 brightness levels, 360° phone holder. Perfect for selfies, video calls, and streams.",
    stock: BigInt(80),
    imageUrl: "https://m.media-amazon.com/images/I/71FNoJrRVML._AC_SX679_.jpg",
    category: "Accessories",
    rating: 4.3,
    price: 899,
    brand: "Portronics",
    company: "Portronics Digital",
    originalPrice: 1999,
    discountPercent: 55n,
    colour: ["White", "Black"],
    connectivity: "wired",
    compatibility: ["iPhone", "Samsung Galaxy", "All Brands"],
    freeDelivery: true,
    deliveryDays: 2,
    tags: ["Ring Lights"],
    hasDeal: true,
    hasCoupon: true,
  },
  {
    id: BigInt(23),
    name: "Magnetic Car Mount Phone Holder",
    description:
      "Universal magnetic car vent mount. 360° rotation, strong N50 magnet, compatible with all smartphones.",
    stock: BigInt(140),
    imageUrl: "https://m.media-amazon.com/images/I/81QwzGy-YNL._AC_SX679_.jpg",
    category: "Car Accessories",
    rating: 4.0,
    price: 349,
    brand: "Zebronics",
    company: "Zebronics India",
    originalPrice: 799,
    discountPercent: 56n,
    colour: ["Black", "Silver"],
    connectivity: "wired",
    compatibility: ["iPhone", "Samsung Galaxy", "All Brands"],
    freeDelivery: false,
    deliveryDays: 2,
    tags: ["Car Mounts"],
    hasDeal: false,
    hasCoupon: false,
  },
  {
    id: BigInt(24),
    name: "Samsung Galaxy Buds2 Pro True Wireless",
    description:
      "3-mic system for intelligent ANC, Hi-Fi 24-bit audio, IPX7 sweat resistance, 29H total playtime.",
    stock: BigInt(40),
    imageUrl: "https://m.media-amazon.com/images/I/71pR3LGEBhL._AC_SX679_.jpg",
    category: "Audio",
    rating: 4.5,
    price: 9999,
    brand: "Samsung",
    company: "Samsung Electronics",
    originalPrice: 17999,
    discountPercent: 44n,
    colour: ["Black", "White", "Grey"],
    connectivity: "bluetooth",
    compatibility: ["Samsung Galaxy", "iPhone", "All Brands"],
    freeDelivery: true,
    deliveryDays: 1,
    tags: ["Earbuds"],
    hasDeal: true,
    hasCoupon: false,
  },
];

export const SHOPPING_IDEAS = [
  "Phone Cases",
  "Wireless Chargers",
  "Earbuds",
  "Power Banks",
  "Screen Protectors",
  "USB-C Cables",
  "Phone Stands",
  "Car Mounts",
  "Armbands",
  "Webcams",
  "Ring Lights",
];

export const BRANDS = [
  "Anker",
  "Belkin",
  "boAt",
  "JBL",
  "Samsung",
  "OnePlus",
  "Realme",
  "Xiaomi",
  "Apple",
  "Bose",
  "Sony",
  "Skullcandy",
  "Mivi",
  "pTron",
  "Zebronics",
  "Portronics",
];

export const COLOUR_SWATCHES = [
  { name: "Black", hex: "#1c1c1c" },
  { name: "White", hex: "#f5f5f5" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "Grey", hex: "#808080" },
  { name: "Blue", hex: "#1a73e8" },
  { name: "Red", hex: "#d32f2f" },
  { name: "Pink", hex: "#e91e63" },
  { name: "Orange", hex: "#ff6f00" },
  { name: "Yellow", hex: "#fbc02d" },
  { name: "Green", hex: "#388e3c" },
  { name: "Teal", hex: "#00796b" },
  { name: "Purple", hex: "#7b1fa2" },
];

export const COMPATIBILITY_OPTIONS = [
  "iPhone",
  "Samsung Galaxy",
  "OnePlus",
  "Xiaomi/Redmi",
  "Realme",
  "All Brands",
];

export const DISCOUNT_TIERS = [10, 25, 35, 50, 60, 70];
