/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router — DO NOT EDIT MANUALLY
// It is OVERWRITTEN by the router at build time.

import {
  createMemoryHistory,
  createRootRoute,
  createRoute,
  createRouter,
} from "@tanstack/react-router";

export interface FileRoutesByPath {
  "/": { id: "/"; path: "/"; fullPath: "/" };
  "/admin": { id: "/admin"; path: "/admin"; fullPath: "/admin" };
  "/manager": { id: "/manager"; path: "/manager"; fullPath: "/manager" };
  "/delivery": { id: "/delivery"; path: "/delivery"; fullPath: "/delivery" };
  "/user": { id: "/user"; path: "/user"; fullPath: "/user" };
  "/collaboration": {
    id: "/collaboration";
    path: "/collaboration";
    fullPath: "/collaboration";
  };
  "/support": { id: "/support"; path: "/support"; fullPath: "/support" };
}

export type RootRouteId = "/";
export type RouteIds = keyof FileRoutesByPath;
export type RoutePaths =
  | "/"
  | "/admin"
  | "/manager"
  | "/delivery"
  | "/user"
  | "/collaboration"
  | "/support";
/* prettier-ignore-end */
